name: Selenium Test Execution

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '00 21 * * *'
  workflow_dispatch:
env:
  TARGET:  "%regex[.*Tests.*],com.vodafone.tests.**,com.vodafone.tests.**"


jobs:
  Chrome_Linux:
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: setup maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.11

      - name: Running Tests
        continue-on-error: true
        run: mvn test -Dtest="${TARGET}" -DexecutionType="LocalHeadless" -DbrowserType="Chrome" clean test

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: Chrome_Linux
          path: "test-outputs/allure-results/*.html"

  Edge_Windows:
      runs-on: Windows-latest
      permissions:
        checks: write
      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: setup java
          uses: actions/setup-java@v4
          with:
            distribution: 'zulu'
            java-version: '21'

        - name: setup maven
          uses: stCarolas/setup-maven@v5
          with:
            maven-version: 3.9.11

        - name: Running Tests
          continue-on-error: true
          run: mvn test -Dtest="${TARGET}" -DexecutionType="LocalHeadless" -DbrowserType="MicrosoftEdge" clean test

        - name: Upload Test Results
          uses: actions/upload-artifact@v4
          with:
            name: Edge_Linux
            path: "test-outputs/allure-results/*.html"







